---
- hosts: nifirh7
  vars:  
    java_archive: jdk-8u191-linux-x64.tar.gz 
    download_url: https://download.oracle.com/otn-pub/java/jdk/8u191-b12/2787e4a523244c269598db4e85c51e0c/jdk-8u191-linux-x64.tar.gz
    path_base: /usr/local/java
    path_archive: /usr/local/java/{{ java_archive }}
#   scala_archive: scala-2.12.8.tgz
#   scala_url: https://downloads.lightbend.com/scala/2.12.8/scala-2.12.8.tgz 
    zookeeper_archive: zookeeper-3.4.12.tar.gz
    zookeeper_url: http://mirror.cc.columbia.edu/pub/software/apache/zookeeper/zookeeper-3.4.12/zookeeper-3.4.12.tar.gz
    nifi_archive: nifi-1.8.0-bin.tar.gz
    nifi_url: https://www.apache.org/dyn/closer.lua?path=/nifi/1.8.0/nifi-1.8.0-bin.tar.gz

  become: yes
  become_method: sudo
  tasks:
    - name: install libselinux-python
      yum:
        name: libselinux-python
        state: present

    - name: make necessary dirs for install
      command: mkdir -p /usr/java

    - name: install java jdk 1.8.x
#     become: yes
#     become_method: sudo
      command: "wget -q -O {{java_archive}} -P {{ path_base }}  --no-check-certificate --no-cookies --header 'Cookie: oraclelicense=accept-securebackup-cookie' {{download_url}}"
#     command: "wget -q -O {{java_archive}} --no-check-certificate --no-cookies --header 'Cookie: oraclelicense=accept-securebackup-cookie' {{download_url}} creates={{path_base}}"

    - name: download scala 2.12.x
      command: "wget -q -O {{scala_archive}} {{scala_url}}" 

    - name: download zookeeper
      command: "wget -q -O {{zookeeper_archive}} {{zookeeper_url}}"

    - namae: download nifi 
      command: "wget -q -O {{nifi_archive}} {{nifi_url}}"

    - name: move downloads
      shell: |
        "for i in /home/vagrant/*;do tar xvf $i;done"
        mv `ls -d */jak*` /usr/java
        mv `ls -d */*` /opt
    
#     command: mv /home/vagrant/* /var
#     become: vagrant
#     become_method: sudo
#     command: mv ~/*.*gz /var/

#   - name: unpack downloads
#     command: for i in 
#   - name: install zookeeper
#     command:

